### ISSUE TITLE
Prerequesits

### ISSUE THREAD

**Issue by reneeb** [dgikiller/mojolicious-plugin-jquery#7]
You list File::Find 3 as a prerequesit, but even Perl 5.20.1 has only version 1.27 shipped. In your Makefile.PL you list perl 5.8.5 as the minimum Perl version, but Mojolicious needs 5.10.1 and Perl 5.8.5 ships File::Find 1.07.

In your JQuery.pm you use File::Spec and Cwd, but do not list them as prerequesits...

I found those issues while installing the module for http://mojo.perl-services.de

**Comment by dgikiller** [comment]
Thank you for your report reneeb, this issue was caused because I didn't specified in the cpanfile the versione required for some dependency. So my release system selected a wrong version of File::Find. This this was fixed with this commit: 911b59f4ed6bf82d65c6f511c5da1ef7a96d0d73
Thank you again for your help. :beers:
